"""updated_at column Expense table

Revision ID: 8da7434b0814
Revises: 9bdd653c0a64
Create Date: 2026-03-26 14:09:33.742060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da7434b0814'
down_revision: Union[str, Sequence[str], None] = '9bdd653c0a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Expenses', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Expenses', 'updated_at')
    # ### end Alembic commands ###
