"""coluna updated_at deve ter server_default=func.now()

Revision ID: b87ac5ff977d
Revises: 8da7434b0814
Create Date: 2026-03-27 11:25:28.884542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87ac5ff977d'
down_revision: Union[str, Sequence[str], None] = '8da7434b0814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Expenses') as batch_op:
        batch_op.alter_column('updated_at', server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Expenses') as batch_op:
        batch_op.alter_column('updated_at', server_default=None)
    # ### end Alembic commands ###
